modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="final_war"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="Final War"
description='''
Adds Quirks from MHA's Final War arc to minecraft via Palladium.
'''

[[dependencies.final_war]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
